@BusTicketReservation_WebApi_Host = https://localhost:44397

# Swagger UI (verify the API is running)
GET {{BusTicketReservation_WebApi_Host}}/swagger
Accept: text/html

###

# Search buses (example)
GET {{BusTicketReservation_WebApi_Host}}/api/bus/search?from=New%20York&to=Boston&journeyDate=2025-10-27
Accept: application/json

###

# IIS Express (sslPort 44397)
GET https://localhost:44397/swagger
Accept: text/html

###
GET https://localhost:44397/api/bus/search?from=New%20York&to=Boston&journeyDate=2025-10-27
Accept: application/json

###
# Kestrel HTTPS profile (7171)
GET https://localhost:7171/swagger
Accept: text/html

###
GET https://localhost:7171/api/bus/search?from=New%20York&to=Boston&journeyDate=2025-10-27
Accept: application/json

###
# Kestrel HTTP profile (5164)
GET http://localhost:5164/swagger
Accept: text/html

###
GET http://localhost:5164/api/bus/search?from=New%20York&to=Boston&journeyDate=2025-10-27
Accept: application/json